apiVersion: v1
kind: ConfigMap
metadata:
  name: fms-orchestr8-config-granite
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    chat_generation:
      service:
        hostname: {{ .Values.orchestrator.llmServiceHostname }}
        port: {{ .Values.orchestrator.llmServicePort }}
    detectors:
      granite-guardian:
        type: text_chat
        service:
          hostname: {{ .Values.graniteGuardian.modelId | base | replace "." "-" }}-predictor
          port: 80
        chunker_id: whole_doc_chunker
        default_threshold: {{ .Values.graniteGuardian.threshold }}
        detector_params:
          risk_name: jailbreak
